name: Synchronisation des repo

on:
  push:
    branches:
      - main

jobs:
  mirror_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Synchroniser le repo avec Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/EpitechPromo2028/B-DOP-200-MPL-2-1-chocolatine-loann.picard-blardone.git