name: Synchronisation du Dépôt

on:
  push:
    branches:
      - main

jobs:
  mirror_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Synchroniser le Dépôt avec Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@github.com:EpitechPromo2028/B-DOP-200-MPL-2-1-chocolatine-loann.picard-blardone.git